# These comments are here to get you started,
# and will go away upon setting the configuration
# for the first time. You can see these comments
# again by using the "configs stock" command.

# For any setting asking for an ID, you can put
# the name of it as well, and the bot will be able
# to use it just fine. Note that it will use the
# first one it finds, and it is case-sensitive.
# For example:
# modrole: "Staff"
# Will work like:
# modrole: 259199371361517569

logging:
  # The bot will forward moderation actions to this channel ID.
  modlog: 
  # The bot will forward server updates to this channel ID.
  serverlog: 
  # The bot will forward user updates to this channel ID.
  userlog: 

staff:
  # The role ID for your admin role.
  adminrole: 
  # The role ID for your moderator role.
  modrole: 
  # The role ID for the Ex-Staff role, if you use one.
  exstaffrole: 
  # The role ID for bots. This will allow bots to speak during lockdowns, and in toss channels.
  botrole: 
  # The role ID for new users, if Raidmode is set to Medium.
  raidrole: 
  # The channel ID for the Staff channel.
  staffchannel: 
  # The channel ID which the bot will forward watched users to.
  watchchannel: 
  # A link to your rules. You can use channels with "<#CHANNELID>",
  # but the bot will not convert a name for you.
  rulesurl: 
  # A link to appeal bans or actions. This will be forwarded to
  # the user upon being banned by the bot.
  appealurl: 
  # If you would like Staff to be notified when a user continuously reply pings someone,
  # set this to the number of times after which the bot will notify Staff. Maximum of 10.
  noreplythreshold: 

toss:
  # The role ID to add to users when performing a toss.
  tossrole: 
  # The category ID for toss sessions to be created in.
  tosscategory: 
  # The channel names that the bot will use when creating sessions.
  # You may only have up to 25.
  tosschannels:

  # The topic for each toss channel.
  tosstopic:

surveyr:
  # The channel ID that the bot will post moderation actions to.
  surveychannel: 
  # The case ID to start from, in the event that you are transitioning from a
  # previous system. If you aren't, simply leave it at 0, or 1 if you do not need a test case.
  startingcase: 
  # Pick from "ban", "unban", "kick", "softban", "timeout", "promotion", "demotion".
  loggingtypes:

  # If using "promotion" or "demotion" in Logging Types, place the role IDs you wish to monitor here.
  loggingroles:


cotd:
  # The role ID to use for a Color of The Day system.
  cotdrole: 
  # The name of the role. For example, "The Rainbow - Pale Blue", where "The Rainbow" is the role name.
  cotdname: 

reaction:
  # If the bot may pull message links and format them nicely.
  embedenable:
  # If the bot may translate messages using reacted flags.
  translateenable:
  # If the bot may autodelete super reactions.
  burstreactsenable:
  # If the bot may automatically adjust names to be readable.
  autoreadableenable:
  # If the bot may randomly laugh at users who have profile effects.
  # Some people get mad at this feature's existence for some reason.
  paidforprofileeffectsenable:
  
roles:
  # Any potential roles to be used with "pls role" should be put here.
  # Please see the following example.
  #
  # - name: Strange Journal    # What you want to call this role.
  #   role: 303555716109565955 # ID of the role.
  #   days: 7                  # Minimum days required to get.
  #   blacklisted:             # Any roles you wish to keep from getting this role.
  #     - 257050851611377666
  #   required:                # Any roles that must be had before getting this role.

  
overrides:
  # To override a command for use with more roles than allowed by default,
  # or to restrict a command to certain roles, configure it here.
  # Please see the following example.
  #
  # - command: kick            # The command you want to override.
  #   roles:                   # The roles this override should apply for.
  #     - 259199371361517569
  #   restrict: false          # Whether to allow (false) or restrict this command to (true) these roles.

metadata:
  version: 7
